

services:
  db:
    image: postgres:15-alpine
    container_name: ldp_bitwarden_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ldp_bitwarden
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ldp_internal
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ldp_bitwarden_backend
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/ldp_bitwarden"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - db
    networks:
      - ldp_internal
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitlooker_backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.bitlooker_backend.entrypoints=websecure"
      - "traefik.http.routers.bitlooker_backend.tls=true"
      - "traefik.http.routers.bitlooker_backend.tls.certresolver=myresolver"
      - "traefik.http.services.bitlooker_backend.loadbalancer.server.port=5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ldp_bitwarden_frontend
    depends_on:
      - backend
    networks:
      - ldp_internal
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitlooker_frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.bitlooker_frontend.entrypoints=websecure"
      - "traefik.http.routers.bitlooker_frontend.tls=true"
      - "traefik.http.routers.bitlooker_frontend.tls.certresolver=myresolver"
      - "traefik.http.services.bitlooker_frontend.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ldp_internal:
  traefik_public:
    external: true
