

services:
  db:
    image: postgres:15-alpine
    container_name: ldp_vault_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ldp_internal
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/ldp-vault-backend:latest
    container_name: ldp_vault_backend
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      JWT_SECRET: "${JWT_SECRET}"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      BACKEND_URL: "https://${API_DOMAIN}"
      FRONTEND_URL: "https://${FRONTEND_DOMAIN}"
      MICROSOFT_CLIENT_ID: "${MICROSOFT_CLIENT_ID}"
      MICROSOFT_CLIENT_SECRET: "${MICROSOFT_CLIENT_SECRET}"
      MICROSOFT_TENANT_ID: "${MICROSOFT_TENANT_ID}"

    depends_on:
      - db
    networks:
      - ldp_internal
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldpvault_backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.ldpvault_backend.entrypoints=websecure"
      - "traefik.http.routers.ldpvault_backend.tls=true"
      - "traefik.http.routers.ldpvault_backend.tls.certresolver=myresolver"
      - "traefik.http.services.ldpvault_backend.loadbalancer.server.port=5000"
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/ldp-vault-frontend:latest
    container_name: ldp_vault_frontend
    depends_on:
      - backend
    networks:
      - ldp_internal
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldpvault_frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.ldpvault_frontend.entrypoints=websecure"
      - "traefik.http.routers.ldpvault_frontend.tls=true"
      - "traefik.http.routers.ldpvault_frontend.tls.certresolver=myresolver"
      - "traefik.http.services.ldpvault_frontend.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ldp_internal:
  traefik_public:
    external: true
